TRASH= ex00/*.class ex01/*.class ex02/*.class ex03/*.class ex04/*.class ex05/*.class

clean:
	rm -rf $(TRASH)

run_ex00:
	javac ex00/Program.java
	java -cp ex00/ Program

run_ex01:
	javac ex01/Program.java
	java -cp ex01/ Program

run_ex02:
	javac ex02/Program.java
	java -cp ex02/ Program

run_ex03:
	javac ex03/Program.java
	java -cp ex03/ Program

run_ex04:
	javac ex04/Program.java
	java -cp ex04/ Program

run_ex05:
	javac ex05/Program.java
	java -cp ex05/ Program
